#!/usr/bin/env bash

# this script toggles the oneko cat
# must have oneko as well as xsetroot installed (xsetroot is to fix the cursor as it breaks every time after I close oneko)
# (at least on my machine)

if pgrep "^oneko$" ; then
    echo "oneko running, killing..."
    pkill -15 "^oneko$"
    sleep 0.2
    xsetroot -cursor_name left_ptr
else
    echo "oneko not running, starting..."
    oneko &
fi