#!/usr/bin/env bash

tty -s || exec konsole -e $0 "$@"

if [ "$EUID" != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

PKGS=$(pacman -Qdtq)

if [[ -z "$PKGS" ]]
then
    echo "No unneeded pacman packages (pacman Qdtq|Rns skipped)"
else
    echo $PKGS
    read -p "Check above list of packages to be removed. Remove? [y/n]" confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1
    echo $PKGS | sudo pacman -Rns -
    echo "Unnessecary packages removed!"
fi

echo "Cleaning cache/repos..."
sudo pacman -Scc
echo "Cache/Repos Cleaned!"
read -n1 -r -p "Press any key to continue..."