# highly modified Pure Prompt

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$sudo\
$line_break\
$python\
$character"""

palette = "custom1"

[palettes.custom1]
teal = "#94e2d5"
mauve = "#cba6f7"
red = "#f38ba8"
green = "#a6e3a1"
surface2 = "#585b70"
yellow = "#f9e2af"

[directory]
style = "teal"

[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "surface2"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "teal"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "surface2"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "surface2"

[sudo]
format = "$symbol "
symbol = "🔴"
disabled = false
