# highly modified Pure Prompt

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$sudo\
$line_break\
$python\
$character"""

palette = "custom1"

[palettes.custom1]
blue = "#9ccfd8"
purple = "#c4a7e7"
red = "#eb6f92"
green = "#31748f"
gray = "#6e6a86"
yellow = "#f6c177"

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "gray"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "blue"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "gray"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "gray"

[sudo]
format = "$symbol "
symbol = "🔴"
disabled = false
