theme = "rose_pine"

[editor]
mouse = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

# https://docs.helix-editor.com/master/configuration.html#editorsoft-wrap-section
[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
### 

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = "│"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
# Use system clipboard
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"

# fix ge to go to end of last line
g = { e = ["goto_last_line", "goto_line_end"] }

# a works goofily at end of line
a = ["move_char_right", "insert_mode"]