#!/usr/bin/env bash
# stupid ahhh python shim with a pause so I can use it in neovim

 # try to prevent errors from nuking shell
set +euo > /dev/null

# execute
python3 "$@" || : # || : because I don't like errors (shell cannot exit or else I cannot read error)

# stupid ahhh hack that consumes all queued/buffered input but only up to 2147483647 chars (signed 32-bit int limit)
while read -r -t 0 -n 2147483647 discard; do read -r; done

# pause
read -n1 -r -p "Press any key to continue..."
