#!/usr/bin/env bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

ARGS="$@"
[ -z "$ARGS" ] || ARGS=" ${ARGS}"

# alacritty --title "NeoVim - Powered by Alacritty" --config-file "$DIR/alacritty-config/alacritty.toml" -e nvim${ARGS}
wezterm start --new-tab nvim${ARGS} &