# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# c-space prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# more sensible splits that open in current directory
bind | split-window -v -c "#{pane_current_path}"
bind _ split-window -h -c "#{pane_current_path}"

# fix colors
set-option -sa terminal-overrides ",xterm*:Tc"

# maus
set -g mouse on

# start windows and panes at 1 because it's on the left of the keyboard
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# changed copy mode keybindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# make swapping windows easier
bind C-M-[ swap-window -t -1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
