# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

# allow lf fm and nvim to be resurrected
set -g @resurrect-processes "lf"
set -g @resurrect-strategy-nvim "session"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# c-space prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

bind C-c source-file ~/.config/tmux/tmux.conf

# more sensible splits that open in current directory
bind _ split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %
# windows also
bind c new-window -c "#{pane_current_path}"

# fix colors
set-option -sa terminal-overrides ",xterm*:Tc"

# set terminal title sync with tmux session title
set-option -g set-titles on
set-option -g set-titles-string "#S"

# faster status interval
set -g status-interval 10

# maus
set -g mouse on

# start windows and panes at 1 because it's on the left of the keyboard
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# changed copy mode keybindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# make swapping windows easier
bind C-left run "tmux swap-window -d -t #{e|-|:#I,1}"
bind C-right run "tmux swap-window -d -t #{e|+|:#I,1}"

# I'm lazy, this is faster
bind C-q kill-session

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
