# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# List of plugins
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "catppuccin/tmux"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "custom"
set -g status-right-length 100 # config from catppuccin/tmux repo
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_status_left_separator "" # setting the separators and stuff
set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}]#[fg=#{@_ctp_status_bg},reverse]█#[none]"
set -gq @catppuccin_window_middle_separator " #[fg=#{@thm_bg},bg=#{@catppuccin_window_number_color}]"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]█#[none]"
set -g @catppuccin_window_default_text " #W" # set window name instead of hostname
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_number_color "#{@thm_mauve}"
set -g @plugin "tmux-plugins/tmux-sensible"

# c-space prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

set-option -g default-shell /usr/bin/zsh

bind C-c source-file ~/.config/tmux/tmux.conf \; display "Reloaded Config!"

# why not
set-option -g history-limit 1000000

bind-key , command-prompt "rename-window '%%'"
bind-key $ command-prompt "rename-session '%%'"

# better pane controls
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# more sensible splits that open in current directory
bind _ split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %
# windows also
bind c new-window -c "#{pane_current_path}"

# fix colors
set-option -sa terminal-overrides ",xterm*:Tc"

# set terminal title sync with tmux session title
set-option -g set-titles on
set-option -g set-titles-string "#S"

# faster status interval
set -g status-interval 10

# maus
set -g mouse on

# start windows and panes at 1 because it's on the left of the keyboard
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# changed copy mode keybindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# make swapping windows easier
bind S-left run "tmux swap-window -d -t #{e|-|:#I,1}"
bind S-right run "tmux swap-window -d -t #{e|+|:#I,1}"

# I'm lazy, this is faster
bind C-q kill-session

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
set -g @plugin "tmux-plugins/tpm"
run '~/.tmux/plugins/tpm/tpm'
