#!/usr/bin/env dash

dconfdump() {
    (
        cd ~/dotfiles/dconf || return 1
        dconf dump /org/cinnamon/ > cinnamon.dconf.ini
        dconf dump /org/nemo/ > nemo.dconf.ini
        dconf dump /org/gtk/ > gtk.dconf.ini
        dconf dump /org/gnome/desktop/ > gnome-desktop.dconf.ini
    )
}

dconfwatch() {
    while read -r data; do
        case "$data" in
            /*)
                # when dconf watch prints output, dump dconf to a file
                # we filter for slashes as output entries always start with a path in dconf
                    # and acting only on lines that begin with a slash prevents dumping dconf
                    # like 3 times unnecessarily
                dconfdump
                ;;
        esac
    done
}

# run dconfdump once at startup to help ensure better sync
dconfdump
# watching the root tree may cause unnecessary writes but it's like a couple kB and idrc
dconf watch / | dconfwatch
notify-send "Warning: dconfd exited." "Error code of dconfwatch function: $?"
