#!/usr/bin/env dash

dconfdump() {
    dconf dump / > /home/jason/dotfiles/dconf.ini
}

dconfwatch() {
    while read -r data; do
        case "$data" in
            /*)
                # when dconf watch prints output, dump dconf to a file
                # we filter for slashes as output entries always start with a path in dconf
                    # and acting only on lines that begin with a slash prevents dumping dconf
                    # like 3 times unnecessarily
                dconfdump
                ;;
        esac
    done
}

# run dconfdump once at startup to help ensure better sync
dconfdump
dconf watch / | dconfwatch
notify-send "Warning: dconfd exited." "Error code of dconfwatch function: $?"
