#!/usr/bin/env python3

# Note: this script should not be run with sudo

import sys
import shutil
import os
import subprocess

from pathlib import Path

HOMETARGET: Path = Path("~" + os.getlogin()).expanduser()
DOTFILEPATH: Path = HOMETARGET.joinpath("dotfiles/dotfiles") # path to root of dotfiles
#HOMETARGET = HOMETARGET.joinpath("dotfiles/test")
PATHS = [
    ".bashrc",
    ".zshrc",
    ".zsh_aliases",
    ".profile",
    ".environment",
    ".gitconfig",

    ".config/nvim/",
    ".config/tmux/",
    ".config/cinnamon/",
    ".config/sublime-text/Packages/User/",
    ".config/autostart/",
    ".config/wezterm/",
    ".config/systemd/user/empty-trash.service",
    ".config/systemd/user/empty-trash.timer",
    ".config/systemd/user/kanata.service",
    ".config/systemd/user/syncthing.service",
    ".config/systemd/user/nix-clean.service",
    ".config/systemd/user/nix-clean.timer",

    ".local/share/nemo/actions/",
    ".local/share/flatpak/overrides/",
    ".local/share/applications/vivaldi-stable.desktop",

    ".var/app/org.flameshot.Flameshot/config/flameshot/"
]

def slink(name: str) -> None:
    global HOMETARGET, DOTFILEPATH
    fpath: Path = HOMETARGET.joinpath(name)
    fpath.parent.mkdir(parents=True, exist_ok=True)
    isdir = name.endswith("/")
    symlink_to(fpath, DOTFILEPATH.joinpath(name), isdir)

def symlink_to(src: Path, tgt: Path, target_is_directory: bool = False) -> None:
    try:
        src.symlink_to(tgt, target_is_directory=target_is_directory)

    except FileExistsError:
        print(f"WARNING: {src} exists, overwriting...")

        if src.is_dir(follow_symlinks=False):
            shutil.rmtree(src)

        else:
            src.unlink()

        src.symlink_to(tgt, target_is_directory=target_is_directory)

    print(f"Symlinked {src}")

def systemd_enable_start(name):
    print(f"Starting `{name}` systemd service/timer")
    subprocess.run(["systemctl", "--user", "enable", name])
    subprocess.run(["systemctl", "--user", "start", name])

def main():
    print(f"DEBUG: Home target detected/set as {HOMETARGET}")
    if HOMETARGET.joinpath(".bashrc").is_symlink():
        print("WARNING: `.bashrc` is a symlink, system is likely already linked")

        if "--force" in sys.argv:
            print("DEBUG: `--force` passed, linking anyways...")

        else:
            print("ERROR: Not linking, pass `--force` to force a link.")
            return 1

    for path in PATHS:
        slink(path)

    print("Reloading systemd daemon")
    subprocess.run(["systemctl", "--user", "daemon-reload"])
    systemd_enable_start("empty-trash.timer")
    systemd_enable_start("kanata")
    systemd_enable_start("syncthing")
    systemd_enable_start("nix-clean.timer")

if __name__ == "__main__":
    main()
