#!/usr/bin/env bash

# https://gist.github.com/matthewpi/08c3d652e7879e4c4c30bead7021ff73
# silverblue/atomic also needs /var/nix/... as well as a buncha other stuff
# this script is hopefully temporary until fedora nix package selinux policy exists

printf "Setting Fedora SELinux contexts...\n"
sudo semanage fcontext -a -t etc_t '/nix/store/[^/]+/etc(/.*)?'
sudo semanage fcontext -a -t lib_t '/nix/store/[^/]+/lib(/.*)?'
sudo semanage fcontext -a -t systemd_unit_file_t '/nix/store/[^/]+/lib/systemd/system(/.*)?'
sudo semanage fcontext -a -t man_t '/nix/store/[^/]+/man(/.*)?'
sudo semanage fcontext -a -t bin_t '/nix/store/[^/]+/s?bin(/.*)?'
sudo semanage fcontext -a -t usr_t '/nix/store/[^/]+/share(/.*)?'
sudo semanage fcontext -a -t var_run_t '/nix/var/nix/daemon-socket(/.*)?'
sudo semanage fcontext -a -t usr_t '/nix/var/nix/profiles(/per-user/[^/]+)?/[^/]+'

printf "Setting additional contexts for non_nixos_gpu_setup...\n"
non_nixos_gpu_setup_location="$(readlink -e \
    "$HOME/.local/state/home-manager/gcroots/current-home/home-path/lib/systemd/system/non-nixos-gpu.service")"

sudo semanage fcontext -a -t systemd_unit_file_t "$non_nixos_gpu_setup_location"
sudo restorecon -v "$non_nixos_gpu_setup_location"