#!/usr/bin/env dash

# check once on start
found_conflicts="$(fd -u "\\.sync-conflict-" ~/obsidian)"

[ -n "$found_conflicts" ] && \
    notify-send "WARNING: Sync conflict(s) detected in ~/obsidian." "$found_conflicts"

inotifywait -mre create ~/obsidian | while read -r dirname events basename;
do
    case "$dirname" in
        /*)
            case "$basename" in
                *".sync-conflict-"*)
                    notify-send "WARNING: Sync conflict detected in ~/obsidian." "$dirname$basename"
                    ;;
            esac
            ;;
    esac
       
done