#!/usr/bin/env bash

set -o pipefail
# get tmux ls and filter for when no tmux sessions are running/other errors
# this script does not handle if there are no tmuxp sessions so uh yeah.
tmuxsessions="$(tmux ls -F "#{session_name}")
" || tmuxsessions="" # (extra newline added here so it only gets added when it's non-empty)

# merge tmux and tmuxp lists to get all available sessions
chosen="$(printf "%s" "${tmuxsessions}$(tmuxp ls)" | sort -u)"
display=()

# add an (inactive) to all inactive session/all session only loaded in tmuxp
tmuxsessions="$(tmux ls -F "#{session_name}")
" || tmuxsessions="" # check the list of tmux sessions again, because I can
while IFS= read -r line || [ -n "$line" ]; do
    if printf "%s" "$tmuxsessions" | grep -q "$line" ; then
        display+=("$line")
    else
        display+=("$line (inactive)")
    fi
done < <(printf "%s" "$chosen")

# plug it into fzf with some formatting
chosen="$(printf "%s\n" "${display[@]}" | fzf)"
# filter out the (inactive) returned if we select an inactive session
chosen="${chosen%' (inactive)'}"

if tmux ls -F "#{session_name}" | grep -q "$chosen" ; then
    if [ -z "$TMUX" ]; then
        # attach the session
        tmux attach -t "$chosen"
    else
        # switch current client to the session
        tmux switchc -t "$chosen"
    fi
else
    # boot up the session in tmuxp
    tmuxp load -y "$chosen"
fi
