#!/usr/bin/env bash

set -eo pipefail

# get sudo perms
if [ "$EUID" != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

function msg {
    main_string="$1"
    shift
    printf "\033[1m\033[7m$main_string\033[0m\n" "$@"
}

# msg!
msg "Starting system updates..."

usern="$(logname)"
msg "Detected username: %s" "$usern"

msg "Updating system Nixpkgs..."
sudo nh os boot "path:///home/jason/dotfiles/nixos" -u -R
msg "Garbage collecting Nix..."
sudo nh clean all --keep 3 --keep-since 25d
msg "Optimising Nix store..."
sudo nix store optimise

msg "Updating Flatpak apps..."
sudo flatpak upgrade -y

msg "Updating Distrobox Zypper..."
sudo -u "$usern" distrobox enter dregsbox -- sudo zypper dup -y
msg "Updating Distrobox pipx packages..."
sudo -u "$usern" distrobox enter dregsbox -- pipx upgrade-all

msg "Updating Neovim plugins..."
sudo -u "$usern" nvim --headless "+Lazy! sync" +qa

msg "Updating Zsh plugins..."
sudo -u "$usern" zsh -c "source ~/.local/share/znaprepos/znap/znap.zsh && znap pull"

msg "Updating tmux plugins..."
sudo -u "$usern" bash -c "~/.tmux/plugins/tpm/bin/update_plugins all"

msg "Emptying trashes..."
sudo -u "$usern" trash-empty 60 -f
sudo trash-empty 60 -f

msg "Writing to update history file..."
sudo -u "$usern" bash -c "date >> ~/.local/share/.yippee_history"

sudo -u "$usern" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$(id -u "$usern")"/bus \
    notify-send "Yippee: Finished updating." "Automatically rebooting in 30 seconds."
read -p "Press Enter to reboot (auto-rebooting in 30 seconds) " -r -t 30 || :
msg "Rebooting..."
sudo systemctl reboot

