#!/usr/bin/env bash

set -eo pipefail

# don't update other stuff if bootstrapping
bootstrap_flag=false
while getopts "b" flag ; do
    case "$flag" in
        b) # Bootstrap instead of updating, skip some tasks
            bootstrap_flag=true
            ;;
        ?)
            printf "Unrecognized option. Use \`-b\` to bootstrap. Use none to update."
            exit 1
            ;;
    esac
done

# sudoloop in the background so only one prompt is necessary
    # (we prevent sudo'ing the script because it breaks user commands and stuff)
sudo -v || exit "$?"
while true;
do
    sleep 60
    kill -0 "$$" || exit
    sudo -nv
done 2>/dev/null &

function msg {
    main_string="$1"
    shift
    printf "\033[1m\033[7m$main_string\033[0m\n" "$@"
}

if [ "$bootstrap_flag" = false ] ; then # Regular update 
    msg "Updating system packages..."
    sudo dnf upgrade --refresh

    msg "Updating Flatpak apps..."
    sudo flatpak update

    msg "Updating Distrobox..."
    distrobox enter arch-toolbox-latest -- paru -Syu

    # Unattended/maintenance tasks
    msg "Updating Gear Lever AppImages..."
    flatpak run it.mijorus.gearlever --update --all -y

    msg "Updating Neovim plugins..."
    nvim --headless "+Lazy! sync" +qa

    msg "Updating Zsh plugins..."
    zsh -c "source ~/.local/share/znaprepos/znap/znap.zsh && znap pull"

    msg "Updating tmux plugins..."
    ~/.tmux/plugins/tpm/bin/update_plugins all

    msg "Emptying trashes..."
    trash-empty 60 -f
    sudo trash-empty 60 -f
else # Bootstrap system
    msg "Updating system packages..."
    sudo dnf upgrade --refresh

    msg "Installing Ansible dependencies..."
    sudo dnf install python3-pip ansible

    msg "Ensuring dotfiles are linked..."
    ~/dotfiles/link.py

    msg "Running Ansible playbook..."
    # this is a script in ~/dotfiles/scripts
    sap

    msg "Creating distrobox..."
    distrobox create -i quay.io/toolbx/arch-toolbox:latest --nvidia --yes
    distrobox enter arch-toolbox-latest -- ~/dotfiles/scripts/distrobox.sh
fi

msg "Writing to yippee history file..."
date >> ~/.local/share/.yippee_history

msg "Waiting for akmods to finish building..."
sudo akmods --force

notify-send "Yippee: Finished updating/bootstrapping." "Automatically rebooting in 30 seconds."
read -p "Press Enter to reboot. (auto-rebooting in 30 seconds) " -r -t 30 || true
msg "Rebooting..."
systemctl reboot || (
    read -p "\`systemctl reboot\` failed. Press Enter to force reboot with \`-i\`. " -r
    systemctl reboot -i
)

