- name: Default playbook
  hosts: all
  become: true
  tasks:
    - name: Set Fedora Release Version Number Variable
      ansible.builtin.command:
        cmd: rpm -E %fedora
      register: fedora_release_number
      changed_when: false
    - ansible.builtin.set_fact:
        fedora_release_number: "{{ fedora_release_number.stdout }}"

    - name: Set Username Variable
      ansible.builtin.command:
        cmd: logname
      register: usern
      changed_when: false
    - ansible.builtin.set_fact:
        usern: "{{ usern.stdout }}"

    - name: Download and Add RPM Fusion GPG keys and repos
      ansible.builtin.dnf:
        name: distribution-gpg-keys
    - ansible.builtin.rpm_key:
        key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ fedora_release_number }}
    - ansible.builtin.rpm_key:
        key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ fedora_release_number }}
    - ansible.builtin.dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_release_number }}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_release_number }}.noarch.rpm

    - name: Import Sublime Text RPM GPG keys
      ansible.builtin.rpm_key:
        key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

    - name: Add Sublime Text Stable repo
      ansible.builtin.command:
        cmd: dnf config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
        creates: /etc/yum.repos.d/sublime-text.repo

    - name: Add Vivaldi Stable repo
      ansible.builtin.command:
        cmd: dnf config-manager addrepo --from-repofile=https://repo.vivaldi.com/stable/vivaldi-fedora.repo
        creates: /etc/yum.repos.d/vivaldi-fedora.repo

    - name: Enable Firefox Dev Copr repo
      community.general.copr:
        name: the4runner/firefox-dev
        state: enabled

    - name: Enable Wezterm Copr repo
      community.general.copr:
        name: wezfurlong/wezterm-nightly
        state: enabled

    - name: Enable Lazygit Copr repo
      community.general.copr:
        name: atim/lazygit
        state: enabled

    - name: Enable Bibata Cursor Copr repo
      community.general.copr:
        name: peterwu/rendezvous
        state: enabled

    - name: Enable keyd Copr repo
      community.general.copr:
        name: alternateved/keyd
        state: enabled

    - name: Install NVIDIA drivers
      ansible.builtin.dnf:
        name:
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda

    - name: Install packages
      ansible.builtin.dnf:
        name:
          # ansible deps/ansible
          - python3-pip
          - ansible

          # language stuff/deps
          - python3-tkinter
          - python3-bpython
          - rust
          - cargo

          # cmdline stuff
          - distrobox
          - git
          - gh
          - zsh
          - tmux
          - python3-tmuxp
          - lazygit # Copr
          - neovim
          - fzf
          - fd-find
          - zoxide
          - keyd # Copr
          - trash-cli

          # apps
          - firefox-dev # Copr
          - vivaldi-stable # 3rd-Party Repo
          - wezterm # Copr
          - sublime-text # 3rd-Party Repo
          - lutris
          - seahorse
          - speedcrunch
          - gpick

          # theming
          - papirus-icon-theme
          - bibata-cursor-themes # Copr

    - name: Add flathub flatpak repo
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      become_user: "{{ usern }}"

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - md.obsidian.Obsidian
          - fm.reaper.Reaper
        method: user
      become_user: "{{ usern }}"

    - name: Install cargo packages
      community.general.cargo:
        name:
          - eza
      become_user: "{{ usern }}"

    - name: Copying keyd config
      ansible.builtin.file: # create necessary config folder
        path: /etc/keyd
        state: directory
    - ansible.builtin.copy:
        src: keyd.conf
        dest: /etc/keyd/default.conf
      register: _keyd_copy
    - ansible.builtin.systemd_service: # ensure service is started and reload config
        name: keyd
        state: started
      when: _keyd_copy.changed
    - ansible.builtin.command:
        cmd: keyd reload
      when: _keyd_copy.changed
      register: _keyd_reload
      changed_when: _keyd_reload.stdout != ""

#    - name: Install pip packages
#      ansible.builtin.pip:
#        name:
#          - 
#        state: present
