- name: Default playbook
  hosts: all
  become: true
  tasks:
    - name: Set Fedora Release Version Number Variable
      ansible.builtin.command:
        cmd: rpm -E %fedora
      register: fedora_release_number
      changed_when: false
    - name: Set Fedora Release Version Number Fact
      ansible.builtin.set_fact:
        fedora_release_number: "{{ fedora_release_number.stdout }}"

    - name: Set Username Variable
      ansible.builtin.command:
        cmd: logname
      register: usern
      changed_when: false
    - name: Set Username Fact
      ansible.builtin.set_fact:
        usern: "{{ usern.stdout }}"

    - name: Download RPM Fusion GPG keys
      ansible.builtin.dnf:
        name: distribution-gpg-keys
    - name: Add RPM Fusion Free GPG key
      ansible.builtin.rpm_key:
        key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ fedora_release_number }}
    - name: Add RPM Fusion Nonfree GPG key
      ansible.builtin.rpm_key:
        key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ fedora_release_number }}
    - name: Add RPM Fusion repo packages
      ansible.builtin.dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_release_number }}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_release_number }}.noarch.rpm

    - name: Import Sublime Text RPM GPG keys
      ansible.builtin.rpm_key:
        key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

    - name: Add Sublime Text Stable repo
      ansible.builtin.command:
        cmd: dnf config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
        creates: /etc/yum.repos.d/sublime-text.repo

    - name: Add Vivaldi Stable repo
      ansible.builtin.command:
        cmd: dnf config-manager addrepo --from-repofile=https://repo.vivaldi.com/stable/vivaldi-fedora.repo
        creates: /etc/yum.repos.d/vivaldi-fedora.repo

    - name: Add LibreWolf repo
      ansible.builtin.command:
        cmd: dnf config-manager addrepo --from-repofile=https://repo.librewolf.net/librewolf.repo
        creates: /etc/yum.repos.d/librewolf.repo

    - name: Add CKAN repo
      ansible.builtin.command:
        cmd: dnf config-manager addrepo --from-repofile=https://ksp-ckan.s3-us-west-2.amazonaws.com/rpm/stable/ckan_stable.repo
        creates: /etc/yum.repos.d/ckan_stable.repo

    - name: Enable Firefox Dev Copr repo
      community.general.copr:
        name: the4runner/firefox-dev
        state: enabled

    - name: Enable Wezterm Copr repo
      community.general.copr:
        name: wezfurlong/wezterm-nightly
        state: enabled

    - name: Enable Lazygit Copr repo
      community.general.copr:
        name: atim/lazygit
        state: enabled

    - name: Enable Bibata Cursor Copr repo
      community.general.copr:
        name: peterwu/rendezvous
        state: enabled

    - name: Enable keyd Copr repo
      community.general.copr:
        name: alternateved/keyd
        state: enabled

    - name: Enable wine/audio Copr repo
      community.general.copr:
        name: patrickl/wine-tkg
        state: enabled

    - name: Install NVIDIA drivers
      ansible.builtin.dnf:
        name:
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda

    - name: Install packages
      ansible.builtin.dnf:
        name:
          # ansible deps/ansible
          - python3-pip
          - ansible

          # language stuff/deps
          - python3-tkinter
          - python3-bpython
          - rust
          - cargo
          - nodejs-bash-language-server
          - dash

          # cmdline stuff
          - distrobox
          - fastfetch
          - btop
          - git
          - gh
          - zsh
          - tmux
          - python3-tmuxp
          - lazygit # Copr
          - neovim
          - bat
          - fzf
          - fd-find
          - ripgrep
          - keyd # Copr
          - trash-cli
          - tldr
          - winetricks
          - yabridge # Copr
          - fuse
          - fuse-libs
          - yt-dlp

          # apps
          - firefox-dev # Copr
          - vivaldi-stable # 3rd-Party Repo
          - wezterm # Copr
          - sublime-text # 3rd-Party Repo
          - librewolf # 3rd-Party Repo
          - obs-studio
          - okular
          - kolourpaint
          - gimp
          - shotcut
          - audacity
          - seahorse
          - speedcrunch
          - gparted
          - pavucontrol
          - gpick
          - dconf-editor
          - flameshot
          - '@virtualization'
          - timeshift
          - qdirstat

          # Game stuff
          - lutris
          - gamemode
          - ckan # 3rd-Party Repo

          # theming
          - papirus-icon-theme
          - bibata-cursor-themes # Copr

    - name: Add Flathub Flatpak repo
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      become_user: "{{ usern }}"

    - name: Install Flatpaks
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - md.obsidian.Obsidian
          - it.mijorus.gearlever
          - io.github.everestapi.Olympus
          - com.github.Anuken.Mindustry
          - org.prismlauncher.PrismLauncher
        method: user
      become_user: "{{ usern }}"

    - name: Install cargo packages
      community.general.cargo:
        name:
          - eza
      become_user: "{{ usern }}"

    - name: Add user "{{ usern }}" to groups
      ansible.builtin.user:
        name: "{{ usern }}"
        groups: keyd,audio
        append: true

    - name: Creating keyd config directory
      ansible.builtin.file: # create necessary config folder
        path: /etc/keyd
        state: directory
    - name: Copying keyd config
      ansible.builtin.copy:
        src: keyd.conf
        dest: /etc/keyd/default.conf
      register: _keyd_copy
    - name: Ensuring keyd systemd service is enabled and started
      when: _keyd_copy.changed
      ansible.builtin.systemd_service:
        name: keyd
        enabled: true
        state: started
    - name: Reloading keyd config
      when: _keyd_copy.changed
      ansible.builtin.command:
        cmd: keyd reload
      register: _keyd_reload
      changed_when: _keyd_reload.stdout != ''

    - name: Creating zram-generator config directory
      ansible.builtin.file: # create necessary config folder
        path: /etc/systemd/zram-generator.conf.d
        state: directory
    - name: Copying zram-generator config
      ansible.builtin.copy:
        src: custom-zram-generator.conf
        dest: /etc/systemd/zram-generator.conf.d/custom-zram-generator.conf

    - name: Enabling Magic SysRq Key
      ansible.posix.sysctl:
        name: kernel.sysrq
        value: '246'

    # these optimizations are from arch/pop! wiki
    - name: Setting vm.swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '180'
    - name: Setting vm.watermark_boost_factor
      ansible.posix.sysctl:
        name: vm.watermark_boost_factor
        value: '0'
    - name: Setting vm.watermark_scale_factor
      ansible.posix.sysctl:
        name: vm.watermark_scale_factor
        value: '125'
    - name: Setting vm.page-cluster
      ansible.posix.sysctl:
        name: vm.page-cluster
        value: '0'

    - name: Setting root partition noatime
      ansible.posix.mount:
        path: /
        src: UUID={{ ansible_mounts | community.general.json_query('[?mount == `/`] | [0].uuid') }}
        fstype: ext4
        opts: defaults,noatime
        dump: '1'
        passno: '1'
        state: present
    - name: Setting root partition noatime
      ansible.posix.mount:
        path: /home
        src: UUID={{ ansible_mounts | community.general.json_query('[?mount == `/home`] | [0].uuid') }}
        fstype: ext4
        opts: defaults,noatime
        dump: '1'
        passno: '2'
        state: present

    - name: Copying Slick Greeter config
      ansible.builtin.copy:
        src: slick-greeter.conf
        dest: /etc/lightdm/slick-greeter.conf

    # performance optimisations for realtime audio and gaming/esync
    - name: Setting nice PAM limit
      community.general.pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nice
        value: '-10'
    - name: Setting memlock PAM limit
      community.general.pam_limits:
        domain: '@audio'
        limit_type: '-'
        limit_item: memlock
        value: 'unlimited'
    - name: Setting rtprio PAM limit
      community.general.pam_limits:
        domain: '@audio'
        limit_type: '-'
        limit_item: rtprio
        value: '99'
    - name: Setting nofile PAM limit
      community.general.pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nofile
        value: '524288'

    - name: Creating udev rules directory
      ansible.builtin.file:
        path: /etc/udev/rules.d
        state: directory
    - name: Copying udev rules config
      ansible.builtin.copy:
        src: custom-udev.rules
        dest: /etc/udev/rules.d/custom-udev.rules

    - name: Ensuring threadirqs parameter is added to grub
      ansible.builtin.replace:
        path: /etc/default/grub
        after: 'GRUB_CMDLINE_LINUX="'
        before: '\n'
        regexp: '(?<!threadirqs)"'
        replace: ' threadirqs"'
      register: _threadirqs_grub_add
    - name: Removing duplicate threadirqs parameters from grub
      ansible.builtin.replace:
        path: /etc/default/grub
        after: 'GRUB_CMDLINE_LINUX="'
        before: '\n'
        regexp: 'threadirqs '
        replace: ''
    - name: Updating grub config
      when: _threadirqs_grub_add.changed
      ansible.builtin.command:
        cmd: grub2-mkconfig -o /etc/grub2.cfg
