#!/bin/sh
# distrobox_binary
# name: dregsbox
if [ -z "${CONTAINER_ID}" ]; then
	exec "/run/current-system/sw/bin/distrobox-enter"  -n dregsbox  --  '/home/jason/.local/share/pipx/venvs/trash-cli/bin/trash-empty'  "$@"
elif [ -n "${CONTAINER_ID}" ] && [ "${CONTAINER_ID}" != "dregsbox" ]; then
	exec distrobox-host-exec '/home/jason/dotfiles/dboxexports/trash-empty' "$@"
else
	exec '/home/jason/.local/share/pipx/venvs/trash-cli/bin/trash-empty' "$@"
fi
