# Generated by check-nix-nvidia script, do not modify
{ config, pkgs, ... }:

{
  nixpkgs.config.nvidia.acceptLicense = true;
  targets.genericLinux.gpu = {
    nvidia = {
      enable = true;
      version = "580.119.02";
      sha256 = "sha256-gCD139PuiK7no4mQ0MPSr+VHUemhcLqerdfqZwE47Nc=";
    };
  };
}
