[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/jason)
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\xf\0\0\0\0\0\0\0#\0\0\x4\xff\0\0\x3;\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0 \0\0\a\x7f\0\0\x4\xf)"

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(1920 935)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x30\0\0\0\x8a\0\0\x5O\0\0\x3\x65\0\0\x2\x30\0\0\0\xaa\0\0\x5O\0\0\x3\x65\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x30\0\0\0\xaa\0\0\x5O\0\0\x3\x65)

[RecentsMRL]
list=file:///home/jason/obsdump/2025-04-23%2021-30-11.mkv, file:///home/jason/DownloadsArchive/2025%20IM%20Collab%20Backing%20Track%20-%202%20bars%20empty.mp3, file:///home/jason/obsdump/2025-04-23%2021-10-13.mkv, file:///home/jason/obsdump/2025-04-23%2020-55-24.mkv, file:///home/jason/obsdump/2025-04-23%2020-53-53.mkv, file:///home/jason/Downloads/VID_20250105_002641_975.mp4, file:///home/jason/Downloads/songofstormssaxtrio-Alto_Saxophone.mp3, file:///home/jason/DownloadsArchive/funni.mov, file:///home/jason/DownloadsArchive/Video.mov, file:///home/jason/DownloadsArchive/haha_lol_funni.mp4, file:///home/jason/DownloadsArchive/paiiin.mp4, file:///home/jason/DownloadsArchive/sussymogus.mp4, file:///home/jason/DownloadsArchive/chumpydumpy.mp3, file:///home/jason/DownloadsArchive/i_am_completely_sane_why_do_you_ask.mp4, file:///home/jason/DownloadsArchive/lingqich.mp4, file:///home/jason/DownloadsArchive/screem.mp3, file:///home/jason/DownloadsArchive/ethanlovaniaa.mp4, file:///home/jason/DownloadsArchive/encredables_uno.mp4, file:///home/jason/DownloadsArchive/encredables_uno.mp3, file:///home/jason/DownloadsArchive/spoodermin_cello.mov, file:///home/jason/Documents/muzaks/pretty_hard.mp3, file:///home/jason/AudioData/Samples/By%20Your%20Side/Piano%20%28isolation%29.wav, file:///home/jason/obsdump/good_kinda_slightly/2025-04-07%2021-09-50.mkv, file:///home/jason/Downloads/slaptongue.mp3, file:///home/jason/obsdump/2025-04-09%2019-21-06.mkv, file:///home/jason/.local/share/Trash/files/EP.1.v1.1080p.mp4, file:///home/jason/.local/share/Trash/files/Amen%20Break%20%2B%20Other%20Drums%20Loops%20%5BhqBSe_4llYw%5D.opus, file:///home/jason/obsdump/2025-04-07%2021-47-17.mkv, file:///home/jason/obsdump/2025-04-07%2021-36-53.mkv, file:///home/jason/obsdump/2025-04-07%2021-00-42.mkv
times=21233, 0, 62175, 0, 0, 0, 5326, 0, 0, 0, 0, 0, 0, 73973, 0, 0, 0, 73025, 0, 0, 0, 0, 156361, 0, 0, 976913, 56827, 152415, 79860, 31216
