[ids]

*

[main]

capslock = esc # caps to esc for vim
rightalt = overload(alt, f5)
esc = layer(nump) # numpad layer!

# swap pageup, home; pagedown, end
pageup = home
pagedown = end
home = pageup
end = pagedown

[shift]

capslock = capslock # shift caps enables caps

[nump]

# numpad stuff!
comma = kp0
dot = kpdot
slash = ^
k = kp1
l = kp2
semicolon = kp3
i = kp4
o = kp5
p = kp6
8 = kp7
9 = kp8
0 = kp9

rightshift = kpplus
apostrophe = kpminus
leftbrace = kpasterisk
minus = kpslash

m = kpleftparen
j = kprightparen
u = macro(a n s)
7 = numlock