[ids]

*

[main]

# caps to esc for vim
capslock = esc
rightalt = overload(alt, f5)
# numpad layer!
esc = layer(nump)

# swap pageup, home; pagedown, end
pageup = home
pagedown = end
home = pageup
end = pagedown

[shift]

# shift caps enables caps
capslock = capslock

[nump]

# numpad stuff!
comma = kp0
dot = kpdot
slash = ^
k = kp1
l = kp2
semicolon = kp3
i = kp4
o = kp5
p = kp6
8 = kp7
9 = kp8
0 = kp9

rightshift = kpplus
apostrophe = kpminus
leftbrace = kpasterisk
minus = kpslash

m = kpleftparen
j = kprightparen
u = macro(a n s)
7 = numlock